mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('general.urls')),
]

general/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class UserProfile(models.Model):
    fio = models.CharField(verbose_name='ФИО', max_length=200)
    phone = models.CharField(verbose_name='Номер телефона', max_length=200)
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE)


class TypesOfService(models.Model):
    name = models.CharField(verbose_name='Наименование типа сервиса', max_length=200)

    def __str__(self):
        return self.name


class Order(models.Model):
    PAYMENT_TYPE_CHOICES = [
        ('0', "Наличные"),
        ('1', "Банковская карта")
    ]
    STATUS_CHOICES = [
        ('0', "Новая"),
        ('1', "В работе"),
        ('2', "Выполнено"),
        ('3', "Отменено")
    ]
    address = models.CharField(verbose_name='Адрес', max_length=200)
    phone = models.CharField(verbose_name='Номер телефона', max_length=200)
    date = models.DateField(verbose_name='Дата')
    time = models.TimeField(verbose_name='Время')
    date_at = models.DateTimeField(auto_now_add=True)
    type = models.ForeignKey(TypesOfService, verbose_name='Тип услуги', on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    description = models.TextField(verbose_name='Описание иной услуги', null=True, blank=True)
    comment = models.TextField(verbose_name='Комментарий при отмене заявки', null=True, blank=True)
    payment_type = models.CharField(
        max_length=1,
        choices=PAYMENT_TYPE_CHOICES,
        verbose_name='Тип оплаты'
    )
    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        default='0',
        verbose_name='Статус заявки'
    )

templates/add_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Страница формирования заявки{% endblock %}

{% block content %}
    <h1>Формирование заявки</h1>

    <form method="post" action="{% url 'add_order' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Добавить заявку</button>
    </form>
{% endblock %}

templates/admin_panel.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Панель администратора{% endblock %}

{% block content %}
    <h1>Управление заявками</h1>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for order in order_list_by_user %}
            <div class="col">
                <div class="card-body">
                    <h5 class="card-title">Заявка № {{ order.pk }}</h5>
                    <p class="card-text">Желаемая дата и время получения услуги: {{ order.date }} - {{ order.time }}</p>
                    <p class="card-text">ФИО заявителя: {{ order.user.userprofile.fio }}</p>
                    <p class="card-text">Контактные данные: {{ order.user.userprofile.phone }}</p>
                    {% if order.type %}<p class="card-text">Вид услуги: {{ order.type }}</p>{% endif %}
                    {% if order.description %}<p class="card-text">Описание иной услуги: {{ order.description }}</p>{% endif %}
                    <p class="card-text">Тип оплаты: {{ order.get_payment_type_display }}</p>
                    <p class="card-text">Статус оказания услуги: {{ order.get_status_display }}</p>
                    {% if order.status == '3' %}
                        <p class="card-text">Причина отмены: {{ order.comment }}</p>
                    {% endif %}

                    {% if order.status == '0' %}
                        <div class="d-flex gap-2">
                            <form method="post" action="{% url 'confirm_order' order.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Подтвердить</button>
                            </form>
                            <a class="btn btn-warning" href="{% url 'cancel_order' order.pk %}">Отклонить</a>
                            <form method="post" action="{% url 'delete_order' order.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        </div>
                    {% endif %}

                    {% if order.status == '1' %}
                        <form method="post" action="{% url 'execute_order' order.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success">Выполнить</button>
                        </form>
                    {% endif %}
                </div>
                <div class="card-footer">
                    <small class="text-body-secondary">{{ order.date_at }}</small>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">"Мой Не Сам"</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Главная</a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Вход</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register_user' %}">Регистрация</a>
                    </li>
                {% else %}
                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_panel' %}">Панель Администратора</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_portal' %}">Портал Администратора</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' %}">Личный Кабинет</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="{% static 'bootstrap.bundle.min.js' %}"></script>

</body>
</html>

templates/cancel_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Страница отмены заявки{% endblock %}

{% block content %}
    <div class="alert alert-info" role="alert">
        <h1>Отклонение заявки № {{ order.pk }}</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Причина отмены</label>
            <textarea name="comment" class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
        </div>
        <button class="btn btn-warning" type="submit">Отменить заявку</button>
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Портал клиниговых услуг "Мой Не Сам"{% endblock %}

{% block content %}
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
{#                https://picsum.photos/600/300#}
                <img src="{% static 'images/image01.jpg' %}" class="d-block w-100"
                     alt="Cleaning 1">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/image02.jpg' %}" class="d-block w-100"
                     alt="Cleaning 2">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images/image03.jpg' %}" class="d-block w-100"
                     alt="Cleaning 3">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Предыдущий</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Следующий</span>
        </button>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}Страница Авторизации{% endblock %}

s{% block content %}
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            Имя пользователя или пароль введены некорректно. Попробуйте снова.
        </div>
    {% endif %}
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="loginField" class="form-label">Логин:</label>
            <input name="username" type="text" class="form-control" id="loginField">
        </div>
        <div class="mb-3">
            <label for="passwordField" class="form-label">Пароль:</label>
            <input name="password" type="password" class="form-control" id="passwordField"/>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary mb-3">Войти</button>
        </div>
    </form>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Страница создания заявки{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{% url 'add_order' %}">Оставить новую заявку</a>

    <h1>История заявок</h1>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for order in order_list_by_user %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Заявка № {{ order.pk }}</h5>
                        <p class="card-text">Желаемая дата и время получения услуги: {{ order.date }} - {{ order.time }}</p>
                        {% if order.type %}<p class="card-text">Вид услуги: {{ order.type }}</p>{% endif %}
                        {% if order.description %}<p class="card-text">Описание иной услуги: {{ order.description }}</p>{% endif %}
                        <p class="card-text">Тип оплаты: {{ order.get_payment_type_display }}</p>
                        <p class="card-text">Статус оказания услуги: {{ order.get_status_display }}</p>
                        {% if order.status == '0' %}
                            <form method="post" action="{% url 'delete_order' order.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        {% endif %}
                    </div>
                    <div class="card-footer">
                        <small class="text-body-secondary">{{ order.date_at }}</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/register_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Регистрация нового пользователя{% endblock %}

{% block content %}
    <h1>Регистрация нового пользователя</h1>
    <form method="post" action="{% url 'register_user' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
{% endblock %}